CREATE FUNCTION op_version( )
RETURNS varchar
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION op_on( )
RETURNS varchar
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION op_test( )
RETURNS varchar
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION op_check( )
RETURNS integer
AS 'MODULE_PATHNAME'
LANGUAGE C;

